version: '3.8'

services:
  db:
    image: postgres:16  # Assure-toi que la version est correcte
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Volume pour stocker les données
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql  # Charge `data.sql` au démarrage
    networks:
      - app-network

  backend:
    build: ./back
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_DATABASE=mydatabase
      - DB_PASSWORD=password
      - DB_PORT=5432
    networks:
      - app-network

  frontend:
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
